#!/bin/bash

xgettext --language=Python --keyword=_ --output=lightdm-manager.pot usr/lib/lightdm-manager/execcmd.py usr/lib/lightdm-manager/functions.py usr/lib/lightdm-manager/lightdm-manager.py usr/lib/lightdm-manager/main.py  usr/lib/lightdm-manager/treeview.py
